		<footer id="footer">
			<div class="wrap">
				<div id="fNav">
					<ul>
						<li><a href="../philosophy/index.html">私たちの姿勢</a></li><!--
						-->
						<li><a href="../service/index.html">サービス</a></li><!--
						-->
						<li><a href="../works/index.html">制作実績</a></li><!--
						-->
						<li><a href="../column/index.html">コラム</a></li><!--
						-->
						<li><a href="../company/index.html">会社概要</a></li><!--
						-->
						<li><a href="index.html">お問い合わせ</a></li><!--
						-->
					</ul>
				</div>
				<div id="copyright">COPYRIGHT&copy; 2003 Webmasters Corporation, ALL RIGHTS RESERVED.</div>
			</div>
		</footer><!--/footer -->
	</div><!--/wrap -->

	<!-- js -->
	<script src="../common/js/jquery-4.0.0.min.js"></script>
	<script src="../common/js/jquery-migrate-4.0.2.min.js"></script>
	<script src="../common/js/jquery.smooth-scroll.min.js"></script>
	<script src="../common/js/common.js"></script>
	<script type="text/javascript">
		var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
		document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	</script>
